function T = matched_output_to_table(out)
%MATCHED_OUTPUT_TO_TABLE Flatten spectral_alignment_windows_robust output.

rows = cell(0,25);
operators = {'adj','lap'};
for oi = 1:numel(operators)
    op = operators{oi};
    S = out.(op);
    for w = 1:numel(S.match)
        for j = 1:numel(S.match{w})
            M = S.match{w}{j};
            topo = S.topology{w}{j};
            for t = 1:numel(M.idxRef)
                met = topo(t).metrics;
                del = topo(t).delta;
                rows(end+1,:) = { ... %#ok<AGROW>
                    op, out.labels{j}, w, min(M.idxRef), max(M.idxRef), ...
                    M.idxRef(t), M.idxX(t), M.cosMatched(t), ...
                    local_get(met,'SAr_ref'), local_get(met,'SAr_x'), local_get(del,'delta_SAr'), ...
                    local_get(met,'smooth_ref'), local_get(met,'smooth_x'), local_get(del,'delta_smooth'), ...
                    local_get(met,'PR_ref'), local_get(met,'PR_x'), local_get(del,'delta_PR'), ...
                    local_get(met,'modR2_ref'), local_get(met,'modR2_x'), local_get(del,'delta_modR2'), ...
                    local_get(met,'MoranI_ref'), local_get(met,'MoranI_x'), local_get(del,'delta_MoranI'), ...
                    S.subspace_aff{w}(j), false};
            end
        end
    end
end

vars = {'operator','target_dataset','window_id','window_k_min','window_k_max', ...
    'reference_k','target_k','matched_cosine', ...
    'SAr_ref','SAr_target','delta_SAr', ...
    'smooth_ref','smooth_target','delta_smooth', ...
    'PR_ref','PR_target','delta_PR', ...
    'modR2_ref','modR2_target','delta_modR2', ...
    'MoranI_ref','MoranI_target','delta_MoranI', ...
    'subspace_affinity','is_selected'};
T = cell2table(rows,'VariableNames',vars);
end

function v = local_get(S,name)
if isfield(S,name), v=S.(name); else, v=NaN; end
end
