function validate_dependencies(config)
%VALIDATE_DEPENDENCIES Check helpers required by the spectral add-on.

required = { ...
    'normalize_operators', ...
    'spectral_fingerprint_windows', ...
    'spectral_alignment_windows_robust', ...
    'rowStandardizeWeights', ...
    'wins_for', ...
    'myfig', ...
    'font'};

missing = required(cellfun(@(f) exist(f,'file') ~= 2, required));
if ~isempty(missing)
    error(['Missing required spectral helper(s): %s. ', ...
        'Run setup_paths.m and confirm matlab/topology_spectra and ', ...
        'matlab/plotting_helpers are present.'], strjoin(missing, ', '));
end

if config.plot_windowed_topology_boxcharts && ...
        exist('delta_topology_boxcharts','file') ~= 2
    error(['plot_windowed_topology_boxcharts requires ', ...
        'delta_topology_boxcharts.m under matlab/topology_spectra.']);
end

if config.run_matched_eigenvectors && ...
        exist('matchpairs','file') ~= 2 && exist('munkres','file') ~= 2
    error(['Matched eigenvector analysis requires matchpairs ', ...
        '(Statistics and Machine Learning Toolbox) or a munkres implementation.']);
end
end
