function validate_config(cfg)
%VALIDATE_CONFIG Validate community-detection configuration fields.

valid_modes = {'precomputed','rerun'};
valid_selection = {'paper','none','score','gamma'};
valid_symmetry = {'average','upper'};

assert(ismember(lower(char(string(cfg.mode))),valid_modes), ...
    'cfg.mode must be ''precomputed'' or ''rerun''.');
assert(ismember(lower(char(string(cfg.selection_mode))),valid_selection), ...
    'cfg.selection_mode must be ''paper'', ''none'', ''score'', or ''gamma''.');
assert(ismember(lower(char(string(cfg.symmetry_mode))),valid_symmetry), ...
    'cfg.symmetry_mode must be ''average'' or ''upper''.');
assert(numel(cfg.coarse.gamma_bounds)==2 && all(cfg.coarse.gamma_bounds>0) && ...
    cfg.coarse.gamma_bounds(2)>cfg.coarse.gamma_bounds(1), ...
    'cfg.coarse.gamma_bounds must contain two increasing positive values.');
assert(cfg.coarse.n_gamma>=2 && cfg.fine.n_gamma>=2, ...
    'Gamma sample counts must be at least 2.');
assert(cfg.fine.n_repetitions>=2, ...
    'cfg.fine.n_repetitions must be at least 2.');
assert(cfg.score_alpha>=0 && cfg.score_alpha<=1, ...
    'cfg.score_alpha must lie between 0 and 1.');
end
